// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCBuilder.Infrastructure.Data;

#nullable disable

namespace PCBuilder.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221183853_MakeComponentsOptional")]
    partial class MakeComponentsOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PCBuilder.Domain.Entities.Cooler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConsumptionWatts")
                        .HasColumnType("int");

                    b.Property<bool>("HasArgb")
                        .HasColumnType("bit");

                    b.Property<int>("HeightMm")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RadiatorSizeMm")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("SupportedSockets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Coolers", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Domain.Entities.Motherboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConsumptionWatts")
                        .HasColumnType("int");

                    b.Property<int>("FormFactor")
                        .HasColumnType("int");

                    b.Property<bool>("HasArgbHeaders")
                        .HasColumnType("bit");

                    b.Property<int>("M2Slots")
                        .HasColumnType("int");

                    b.Property<int>("MaxRamCapacityGb")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PcieGeneration")
                        .HasColumnType("int");

                    b.Property<int>("PcieX16Slots")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RamSlots")
                        .HasColumnType("int");

                    b.Property<int>("SataSlots")
                        .HasColumnType("int");

                    b.Property<int>("Socket")
                        .HasColumnType("int");

                    b.Property<int>("SupportedRam")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Motherboards", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Domain.Entities.PCBuild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CoolerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MotherboardId")
                        .HasColumnType("int");

                    b.Property<int?>("PcCaseId")
                        .HasColumnType("int");

                    b.Property<int?>("PowerSupplyId")
                        .HasColumnType("int");

                    b.Property<int>("ProcessorId")
                        .HasColumnType("int");

                    b.Property<int?>("RamId")
                        .HasColumnType("int");

                    b.Property<int>("RamQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryStorageId")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryStorageQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryVideoCardId")
                        .HasColumnType("int");

                    b.Property<int?>("StorageId")
                        .HasColumnType("int");

                    b.Property<int>("StorageQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("VideoCardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoolerId");

                    b.HasIndex("MotherboardId");

                    b.HasIndex("PcCaseId");

                    b.HasIndex("PowerSupplyId");

                    b.HasIndex("ProcessorId");

                    b.HasIndex("RamId");

                    b.HasIndex("SecondaryStorageId");

                    b.HasIndex("SecondaryVideoCardId");

                    b.HasIndex("StorageId");

                    b.HasIndex("VideoCardId");

                    b.ToTable("PCBuilds");
                });

            modelBuilder.Entity("PCBuilder.Domain.Entities.PcCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConsumptionWatts")
                        .HasColumnType("int");

                    b.Property<int>("MaxCpuCoolerHeightMm")
                        .HasColumnType("int");

                    b.Property<int>("MaxGpuLengthMm")
                        .HasColumnType("int");

                    b.Property<int>("MaxMotherboardSize")
                        .HasColumnType("int");

                    b.Property<int>("MaxPsuLengthMm")
                        .HasColumnType("int");

                    b.Property<int>("MaxRadiatorSizeMm")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupportedPsuFormFactor")
                        .HasColumnType("int");

                    b.Property<bool>("SupportsLiquidCooling")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PcCases", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Domain.Entities.PowerSupply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Certification")
                        .HasColumnType("int");

                    b.Property<int>("ConsumptionWatts")
                        .HasColumnType("int");

                    b.Property<int>("FormFactor")
                        .HasColumnType("int");

                    b.Property<int>("LengthMm")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Modularity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Wattage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PowerSupplies", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Domain.Entities.Processor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConsumptionWatts")
                        .HasColumnType("int");

                    b.Property<bool>("HasIntegratedGraphics")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludesStockCooler")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Socket")
                        .HasColumnType("int");

                    b.Property<int>("SupportedRam")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Processors", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Domain.Entities.Ram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CapacityGb")
                        .HasColumnType("int");

                    b.Property<int>("ConsumptionWatts")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModulesCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SpeedMhz")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rams", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Domain.Entities.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CapacityGb")
                        .HasColumnType("int");

                    b.Property<int>("ConsumptionWatts")
                        .HasColumnType("int");

                    b.Property<int>("InterfaceType")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReadSpeedMb")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Storages", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Domain.Entities.VideoCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConsumptionWatts")
                        .HasColumnType("int");

                    b.Property<int>("LengthMm")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PcieGeneration")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VramGb")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VideoCards", (string)null);
                });

            modelBuilder.Entity("PCBuilder.Domain.Entities.PCBuild", b =>
                {
                    b.HasOne("PCBuilder.Domain.Entities.Cooler", "Cooler")
                        .WithMany()
                        .HasForeignKey("CoolerId");

                    b.HasOne("PCBuilder.Domain.Entities.Motherboard", "Motherboard")
                        .WithMany()
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCBuilder.Domain.Entities.PcCase", "PcCase")
                        .WithMany()
                        .HasForeignKey("PcCaseId");

                    b.HasOne("PCBuilder.Domain.Entities.PowerSupply", "PowerSupply")
                        .WithMany()
                        .HasForeignKey("PowerSupplyId");

                    b.HasOne("PCBuilder.Domain.Entities.Processor", "Processor")
                        .WithMany()
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCBuilder.Domain.Entities.Ram", "Ram")
                        .WithMany()
                        .HasForeignKey("RamId");

                    b.HasOne("PCBuilder.Domain.Entities.Storage", "SecondaryStorage")
                        .WithMany()
                        .HasForeignKey("SecondaryStorageId");

                    b.HasOne("PCBuilder.Domain.Entities.VideoCard", "SecondaryVideoCard")
                        .WithMany()
                        .HasForeignKey("SecondaryVideoCardId");

                    b.HasOne("PCBuilder.Domain.Entities.Storage", "Storage")
                        .WithMany()
                        .HasForeignKey("StorageId");

                    b.HasOne("PCBuilder.Domain.Entities.VideoCard", "VideoCard")
                        .WithMany()
                        .HasForeignKey("VideoCardId");

                    b.Navigation("Cooler");

                    b.Navigation("Motherboard");

                    b.Navigation("PcCase");

                    b.Navigation("PowerSupply");

                    b.Navigation("Processor");

                    b.Navigation("Ram");

                    b.Navigation("SecondaryStorage");

                    b.Navigation("SecondaryVideoCard");

                    b.Navigation("Storage");

                    b.Navigation("VideoCard");
                });
#pragma warning restore 612, 618
        }
    }
}
